### ISSUE TITLE
Uncaught TypeError: this.element.querySelector is not a function

### ISSUE THREAD

**Issue by cariz** [Arignir/Epitech-norm-linter#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [epitech-norm-linter](https://github.com/Arignir/Epitech-norm-linter) package 1.12.3

### Stack Trace

Uncaught TypeError: this.element.querySelector is not a function

```
At /Users/cariz/.atom/packages/epitech-norm-linter/node_modules/atom-package-deps/lib/view.js:41

TypeError: this.element.querySelector is not a function
    at View.advance (/packages/epitech-norm-linter/node_modules/atom-package-deps/lib/view.js:41:36)
    at /packages/epitech-norm-linter/node_modules/atom-package-deps/lib/main.js:53:16
    at stdout (/packages/epitech-norm-linter/node_modules/atom-package-deps/lib/helpers.js:24:11)
    at Socket.<anonymous> (/private/var/folders/gx/tmcxk_891sv6kjc52gc4qs3c0000gn/T/AppTranslocation/7E0C5C2A-21BC-4B4A-BA6E-48A924CE99A5/d/Atom.app/Contents/Resources/app/src/buffered-process.js:212:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
 21x -3:39.7.0 core:backspace (input.hidden-input)
     -1:23.7.0 core:confirm (input.hidden-input)
     -0:56.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
epitech-norm 0.3.4 
epitech-norm-linter 1.12.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
phoenix-epitech-headers 0.2.3 
```

**Comment by Arignir** [comment]
Won't fix, not working on this project anymore. Feel free to fork the project if you want to.
